rng(1);
labs = {'lab1_bsc_repetition','lab2_parity','lab3_distance', ...
        'lab4_hamming_syndrome','lab4b_hamming_toolbox', ...
        'lab5_crc_cyclic','lab6_gf8','lab7_bch_rs','lab8_shannon', ...
        'lab9_xor_erasure','lab10_lt_fountain','lab11_ldpc', ...
        'lab12_convolutional','lab13_indel_vt','lab14_constraint'};
for i = 1:numel(labs)
    fprintf('\n===== %s =====\n', labs{i});
    try, run(labs{i}); catch err, fprintf('ERROR: %s\n', err.message); end
end
close all
